from pathlib import Path

import pytest

from mofbuilder.io.cif_writer import CifWriter
from mofbuilder.io.gro_writer import GroWriter
from mofbuilder.io.pdb_reader import PdbReader
from mofbuilder.io.pdb_writer import PdbWriter
from mofbuilder.io.xyz_reader import XyzReader
from mofbuilder.io.xyz_writer import XyzWriter


def _sample_data_lines():
    return [
        ["C", "C1", 1, "MOL", 1, 0.0, 0.0, 0.0, 1.0, 0.0, "C"],
        ["O", "O2", 2, "MOL", 1, 1.0, 0.0, 0.0, 1.0, 0.0, "O"],
    ]


def test_xyz_writer_and_reader_roundtrip(tmp_path):
    out = tmp_path / "roundtrip.xyz"
    writer = XyzWriter()
    writer.write(filepath=str(out), header="test xyz", lines=_sample_data_lines())

    assert out.exists()
    reader = XyzReader(filepath=str(out))
    reader.read_xyz()
    assert reader.data is not None
    assert reader.data.shape[0] == 2


def test_xyz_writer_get_xyzlines_has_expected_header():
    writer = XyzWriter()
    lines = writer.get_xyzlines(header="hello", lines=_sample_data_lines())
    assert lines[0].strip() == "2"
    assert lines[1].strip() == "hello"


def test_pdb_writer_and_reader_roundtrip(tmp_path):
    out = tmp_path / "roundtrip.pdb"
    writer = PdbWriter()
    writer.write(filepath=str(out), header="HEADER\n", lines=_sample_data_lines())

    assert out.exists()
    reader = PdbReader(filepath=str(out))
    reader.read_pdb(recenter=False)
    assert reader.data is not None
    assert reader.data.shape[0] == 2


def test_gro_writer_writes_and_reader_parses(tmp_path):
    out = tmp_path / "roundtrip.gro"
    writer = GroWriter()
    writer.write(filepath=str(out),
                 lines=_sample_data_lines(),
                 box=[20.0, 20.0, 20.0],
                 triclinic=False)

    assert out.exists()
    text = out.read_text(encoding="utf-8")
    assert "Generated by MofBuilder" in text


def test_gro_writer_triclinic_requires_six_box_values(tmp_path):
    out = tmp_path / "bad_triclinic.gro"
    writer = GroWriter()
    with pytest.raises(AssertionError):
        writer.write(filepath=str(out),
                     lines=_sample_data_lines(),
                     box=[20.0, 20.0, 20.0],
                     triclinic=True)


def test_cif_writer_writes_required_blocks(tmp_path):
    out = tmp_path / "test_out.cif"
    writer = CifWriter()
    writer.write(
        filepath=str(out),
        header="MOFbuilder-test",
        lines=_sample_data_lines(),
        supercell_boundary=[10.0, 10.0, 10.0],
        cell_info=[10.0, 10.0, 10.0, 90.0, 90.0, 90.0],
    )

    assert out.exists()
    text = out.read_text(encoding="utf-8")
    assert "_cell_length_a" in text
    assert "_atom_site_fract_x" in text
